version: '{build}'

configuration:
  - RelWithDebInfo

environment:
  SAMP_SDK_ROOT: sdk

  matrix:
  - STATIC: ON
  - STATIC: OFF

install:

  - RefreshEnv


build_script:
	- make YSF

artifacts:
  - path: YSF.zip
    name: Binaries
